### PR TITLE
Added NFC support

### PR DESCRIPTION
**Pull request by hervehobbes**
Hello,

I have added support for NFC passes.

Bye

### CODE REVIEW

**Review by eymengunay — APPROVED** [review]
Hi @hervehobbes, thanks for the PR! it is merged.

**Comment by JeroenMoonen** [comment]
Can this be fixed and merged? Thanks!

**Comment by eymengunay** [comment]
Hi @hervehobbes ,

I don't know what happened but I was sure that I had merged your PR. Sorry about the delay and thanks again for the contribution.

It is tagged under [v3.1.0](https://github.com/eymengunay/php-passbook/releases/tag/v3.1.0).

**Comment by eymengunay** [comment]
@JeroenMoonen thank you for the heads up!

**Comment by hervehobbes** [comment]
No problem.

**Pull request merged**
