### PR TITLE
Allow one to specify name of pkpass file

### PR DESCRIPTION
**Pull request by sashahilton00**
Added ability to specify name of the pkpass file.

### CODE REVIEW

**Comment by sashahilton00** [comment]
Not sure what is going on with Scrutinizer though...

**Comment by g-** [comment]
Thanks for the contribution! Setting the pass name is certainly a useful addition. There are three things that I'd like to see addressed with this pull request.

1. A PassFactory may package many different passes and it does not maintain state for individual passes, so the constructor and member variable aren't best suited for setting and storing the passName. What about moving this as an optional parameter of the package() method?

2. Using a ternary operator and single return statement would make getPassName more concise.

3. There need to be tests. Please include tests that verify the expected behaviour for the changes made. Because this is dealing with packaging, you may want to use the setSkipSignature() method to avoid the tests failing due to missing certificates. See existing tests in the PassFactoryTest class.

**Comment by g-** [comment]
@eymengunay Do you know what is the issue with Scrutinizer?

**Comment by sashahilton00** [comment]
Hi, will look into correcting it tomorrow, could you elaborate on what a ternary operator is please? I am useless with technical terms ;)

**Comment by eymengunay** [comment]
@g- @sashahilton00 There were deprecated options in the configuration file, it should work now.

**Comment by g-** [comment]
The ternary operator is the ?: combination. It is convenient for a return statement that is returning one of two options. For example:

`return strlen($str) != 0 ? $str : 'default'`

**Comment by g-** [comment]
Thanks @eymengunay.

**Comment by sashahilton00** [comment]
Ah right, I never knew that the aforementioned structure had a name. Will change it later.
On Mon, Apr 4, 2016 at 10:26 a.m., g <notifications@github.com> wrote:
Thanks @eymengunay [https://github.com/eymengunay] .

**Comment by sashahilton00** [comment]
Will close this PR, and open new one as I accidentally switched branch

**Pull request closed without merging**
